[package]
name = "tetrs_terminal"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
crossterm = "0.27.0"
tetrs_engine = { path = "../tetrs_engine" }
